apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: default
data:
  index.html: |
    <html>
    <header><title>Steg 4</title></header>
    <body>
    Steg 4 fullført!
    </body>
    </html>
